spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health, metrics, logfile"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled:
        true
  health:
    defaults:
      enabled: true

logging:
  file:
    name: "app.log"